// webapp/src/components/Room.tsx
import { faLightbulb } from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import * as React from 'react';
import { Subscription } from 'rxjs';
import { UpdateLightAction } from '../model/action';
import { connection } from '../model/hardware-connection';
import { Light } from '../model/lights';

const globalStyle: React.CSSProperties = {
	display: "grid",
	placeContent: "center",
	fontSize: "2em",
}

interface Properties {
	name: string;
	light: Light;
}

interface State {
	state: boolean;
	pwm: number;
}

export class Room extends React.Component<Properties, State> {

	private lightSubscription?: Subscription;

	constructor(props: Properties) {
		super(props)
		this.state = { state: false, pwm: 0 }
	}

	render() {
		const { light, name } = this.props;
		const { state, pwm } = this.state;
		console.log('render room', light, name, state, pwm);
		let style: React.CSSProperties = {
			gridArea: name,
			backgroundColor: state ? 'yellow' : 'white',
			color: state ? "black" : "gray",
			...globalStyle
		}
		return <div style={style} onClick={() => connection.dispatch(new UpdateLightAction(light, !state, pwm))}>
			<FontAwesomeIcon icon={faLightbulb} />
		</div>
	}

	componentDidMount() {
		this.lightSubscription = connection.lights$
			.subscribe(({ state, pwm }) => {
				let { light: idx } = this.props;
				let { state: oldState, pwm: oldPwm } = this.state;
				let newState = state.get(idx);
				let newPwm = pwm[idx];
				if (newState !== oldState || newPwm !== oldPwm) {
					this.setState({
						state: newState,
						pwm: newPwm
					})
				}
			});
	}

	componentWillUnmount() {
		this.lightSubscription?.unsubscribe();
	}

}

// angular-webapp/src/app/room/room.component.ts
import { Component, HostBinding, HostListener, Input } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { faLightbulb } from '@fortawesome/free-regular-svg-icons';
import { Subscription } from 'rxjs';
import { HardwareConnectionService } from '../hardware-connection.service';
import { LoadingComponent } from '../loading/loading.component';
import { UpdateLightAction } from '../model/action';
import { Light } from '../model/lights';

@Component({
  selector: 'app-room',
  templateUrl: './room.component.html',
  styleUrls: ['./room.component.scss']
})
export class RoomComponent {

  faLightbulb = faLightbulb;

  private lightSubscription?: Subscription;
  private spinner?: MatDialogRef<any>;

  @Input()
  @HostBinding('style.grid-area')
  name!: string;

  @Input()
  light!: Light;

  state = false;
  pwm = 255;

  @HostBinding('style.background-color')
  get backgroundColor() { return this.state ? 'yellow' : 'white' };

  @HostBinding('style.color')
  get color() { return this.state ? 'black' : 'gray'; }

  constructor(
    private matDialog: MatDialog,
    private connection: HardwareConnectionService
  ) { }

  ngOnInit() {
    this.lightSubscription = this.connection.lights$.subscribe(lights => {
      this.spinner?.close();
      this.state = lights.state.get(this.light);
      this.pwm = lights.pwm[this.light];
    })
  }

  ngOnDestroy() {
    this.lightSubscription?.unsubscribe();
  }


  @HostListener('click')
  click() {
    this.spinner?.close();
    this.spinner = this.matDialog.open(LoadingComponent);
    this.connection.dispatch(new UpdateLightAction(this.light, !this.state, this.pwm))
  }

}

<fa-icon [icon]="faLightbulb"></fa-icon>
