// webapp/src/components/House.tsx
import React from "react";
import { Room } from "./Room";

const rooms = [
	"lavanderia",
	"cozinha",
	"joicce",
	"copa",
	"sala",
	"jeronimo",
	"celsli",
	"varanda"
]

export class House extends React.Component {

	render() {
		console.log('render house')
		return <div className="house">
			{rooms.map((name, i) => (<Room key={i} name={name} light={i}></Room>))}
		</div>
	}

}

// angular-webapp/src/app/house/house.component.ts
import { Component } from '@angular/core';
import { faLightbulb } from '@fortawesome/free-regular-svg-icons';

@Component({
  selector: 'app-house',
  templateUrl: './house.component.html',
  styleUrls: ['./house.component.scss']
})
export class HouseComponent {

  faLightbulb = faLightbulb;

  rooms = [
    "lavanderia",
    "cozinha",
    "joicce",
    "copa",
    "sala",
    "jeronimo",
    "celsli",
    "varanda"
  ]

  trackByIdx = (i: number) => i;

}

<app-room *ngFor="let name of rooms; trackBy: trackByIdx; index as i; " [name]="name" [light]="i"></app-room>
